name: Deploy Snake to VPS

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: deploy-snake
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Déploiement de Snake Game"
            cd /var/www/snake-game
            
            if [ ! -d ".git" ]; then
              git clone https://github.com/${{ github.repository }} .
            else
              git pull origin main
            fi
            
            # Permissions Ubuntu 24
            find . -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" \) -exec chmod 644 {} \;
            find . -type d -exec chmod 755 {} \;
            
            touch index.html
            echo "✅ Snake Game déployé avec succès"

      - name: Health check
        run: |
          sleep 2
          curl -I https://snake.placoste.dev | head -n 5
